create schema library_book;
create table person
(
    person_id integer generated by default as identity primary key,
    full_name        varchar(100) not null
        unique
        constraint person_full_name_check
            check (char_length((full_name)::text) >= 8),
    year_of_birthday integer      not null
        constraint person_year_of_birthday_check
            check (year_of_birthday > 0),
    password         varchar,
    login            varchar,
    role             varchar
);

create table book
(
    book_id         integer generated by default as identity
        primary key,
    person_id       integer
                                 references person
                                     on delete set null,
    title           varchar(100) not null,
    year_of_realise integer      not null
        constraint book_year_of_realise_check
            check (year_of_realise > 0),
    author          varchar(50)  not null,
    taken_at        timestamp
);

